### ISSUE TITLE
能否注释一下程序，并且完善一下readme

### ISSUE THREAD

**Issue by meanmee** [huashiyiqike/LSTM-MATLAB#1]
你好，我是中国石油大学（华东）的一名本科生，最近在看rnn相关的论文，看完后都不能很好地理解，请问能不能把您的程序注释一下，十分感谢。我的gitoschina 网址：http://git.oschina.net/meanmee QQ：379940325，先谢谢您的指导。

**Comment by meanmee** [comment]
n is the imaginary
layer consisting of the nodes that have direct connections with the nodes in question between time
steps. For example, for layer l, n consists of l, !,  of the last time step, and input units, shown in
the connections in Fig.，您的论文中这句话我不理解，能解释一下吗

**Comment by huashiyiqike** [comment]
n is just a notation for convenience; you should look carefully at the picture, and the code as well, which I believe is self-explanatory with the variable names given.

**Comment by MJ78037002** [comment]
Thank you very much for this process，can you comment on your program?
my email: 78037002@qq.com
