### ISSUE TITLE
How to use LSTM for multiclass classification problem

### ISSUE THREAD

**Issue by tzczsq** [huashiyiqike/LSTM-MATLAB#2]
Hi, I am interested in your LSTM-MATLAB code.
I want to use LSTM code for multiclass classification problem.
Coud you please give an example for the use of LSTM for classfication?
Thanks.

**Comment by huashiyiqike** [comment]
It is not implemented in this project. For using LSTM for sequence classification, you can take a look at Alex Graves's PHD thesis.
