### ISSUE TITLE
Training and Testing

### ISSUE THREAD

**Issue by AziziShekoofeh** [huashiyiqike/LSTM-MATLAB#4]
Hi,

I cannot find the main function, where I can call something like:

model = trainLSTM(xtrain,ytrain, other params) 
predict = model(xtest)

Can you elaborate on this or provide a simple example for that? 
Also, in your example what do the dimensions of 'data' represent?

Thanks,
Minerva

**Comment by huashiyiqike** [comment]
I didn't write the code in that way, but I got lots of responses like yours. I will appreciate if you'd like to contribute for this feature. The dimensions are so set for the experiment, e.g. two numbers with a flag constitute three dimensions.
