### ISSUE TITLE
question about training data

### ISSUE THREAD

**Issue by stutys** [huashiyiqike/LSTM-MATLAB#5]
I'm new in lstm, and confusing about the training data. Could you introduce your generating data, [data,mask,test,masktest] please?  
In fact, i don't understand how do the data flow through lstm? thanks very much!

**Comment by huashiyiqike** [comment]
read the README: The dataset and labels etc follows the original LSTM paper in 1997. You can print the data to see. no magic here.

**Comment by stutys** [comment]
README is not so useful for new dataset. no matter, thx!
