### ISSUE TITLE
how to provide my 4096 features to LSTM-MATLAB?

### ISSUE THREAD

**Issue by ganav** [huashiyiqike/LSTM-MATLAB#7]
Hello Mr
I have feature txt files, each txt file represents a feature of an image. A text file has 4096 numbers that have been extracted from fc7 layer of VGG16-net. I want to provide these features to your LSTM-MATLAB for training LSTM and testing for result.

I cannot find explanation that describes how and where to define path of my database in the aStart.m
Also where it generates trained weight, how to test and how to train.

I am going to use your project in my research test for my new journal paper.
Thank you

**Comment by huashiyiqike** [comment]
sorry for the late response. you may need to write an io function to input your data, and configure the network to receive the exact dimensions of data.

**Comment by alijavidani** [comment]
@ganav : Hi, Did your problem solved?
I faced the same issue. Could you please help me?
Thanks in advance.

**Comment by ganav** [comment]
@alijavidani Hi bro. 
I have given up the project but i have started another project and completed my project.
I used  tensorflow+keras, ubuntu OS and python. I have used this LSTM+CNN and LSTM stacked CNN

https://blog.coast.ai/five-video-classification-methods-implemented-in-keras-and-tensorflow-99cad29cc0b5 

It provides source you should read and edit the code. After training i extract 4096 features and i can train lstm here.
